# .github/workflows/cd.yml
name: FastAPI Continuous Delivery

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: List directory contents
      run: ls -R  # This will list files and directories in the workspace
    # - name: Run tests
    #   run: |
    #     pytest  # Assuming you have tests in place

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Only run deploy after the build job passes
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your SSH key to GitHub secrets

    - name: List directory contents
      run: ls -R  # This will list files and directories in the workspace
    
    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H 157.173.114.28 >> ~/.ssh/known_hosts
        
    - name: Copy files via SSH
      run: |
        scp app.py requirements.txt root@157.173.114.28:/root/public/python-get-youtube-link
      
    - name: Install dependencies
      run: |
        ssh root@157.173.114.28 "cd public/python-get-youtube-link && python3 -m venv venv && source venv/bin/activate && python3 -m pip install pip && pip install --upgrade pip && pip install -r requirements.txt"

        
    - name: Restart FastAPI service
      run: |
        ssh root@157.173.114.28 "sudo systemctl restart fastapi-app"  # Replace with your app's service
